# Generated by Django 4.1.1 on 2022-10-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixmodel',
            name='audio',
            field=models.FileField(upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='mixmodel',
            name='image',
            field=models.ImageField(upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='mixmodel',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
