# Generated by Django 4.1.1 on 2022-12-29 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mixadmin', '0002_alter_mixmodel_audio_alter_mixmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mixmodel',
            name='audio',
            field=models.FileField(upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='mixmodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
