# Generated by Django 4.1.1 on 2022-12-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixadmin', '0003_mixmodel_created_at_alter_mixmodel_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixmodel',
            name='tag2',
            field=models.CharField(default='standard', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mixmodel',
            name='tag',
            field=models.CharField(max_length=25),
        ),
    ]
