# Generated by Django 4.1.1 on 2022-12-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixadmin', '0004_mixmodel_tag2_alter_mixmodel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixmodel',
            name='tag',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='mixmodel',
            name='tag2',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
