# Generated by Django 4.1.1 on 2023-02-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mixadmin', '0005_alter_mixmodel_tag_alter_mixmodel_tag2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackTitle', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='mixmodel',
            old_name='created_at',
            new_name='date',
        ),
        migrations.AddField(
            model_name='mixmodel',
            name='creator',
            field=models.CharField(default='blank', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrackToMix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('playlistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixadmin.mixmodel')),
                ('trackId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixadmin.track')),
            ],
        ),
    ]
