# Generated by Django 4.1.1 on 2023-02-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixadmin', '0006_track_rename_created_at_mixmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixmodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mixmodel',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
