# Generated by Django 4.1.1 on 2023-03-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixadmin', '0008_alter_mixmodel_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mixmodel',
            old_name='date',
            new_name='created_at',
        ),
    ]
