# Generated by Django 4.1.1 on 2023-03-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixadmin', '0009_rename_date_mixmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixmodel',
            name='description',
            field=models.TextField(default='No description available.'),
            preserve_default=False,
        ),
    ]
