# Generated by Django 4.1.1 on 2023-03-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixadmin', '0010_mixmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixmodel',
            name='description',
            field=models.TextField(default='No description available.'),
        ),
    ]
