# Generated by Django 4.1.1 on 2023-03-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixadmin', '0011_alter_mixmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixmodel',
            name='backgroundImg',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
